In [ ]:
import numpy as np

In [ ]:
x = [[1,2],[3,4]]
nx = np.array(x)

In [ ]:
print(nx.sum())
print(nx.min())
print(nx.max())
print(nx.mean())
print(nx.std())
print(nx.var())

In [ ]:
type(nx)

In [ ]:
print(nx.shape) # shape of matrix
print(nx.size)  # total elements
print(nx.dtype)  # type of elements

functions to create matrix
- `arange`: create a range of numbers
- `linspace`: create a matrix of specified number of elements
- `ones`: create a matrix of ones
- `zeros`: create a matrix of zeros
- `random.randint`: create a matrix of random integers
- `random.rand`: create a matrix of random floats
- `diag`: create a matrix with diagonal elements

In [ ]:
a = np.arange(1, 50)
print(a)

In [ ]:
np.arange(1, 5, .05)

In [ ]:
np.linspace(1, 100, 10)

In [ ]:
np.ones(10)

In [ ]:
np.ones((3,3))

In [ ]:
np.ones((3,6), dtype=int)

In [ ]:
np.random.randint(1, 100, 10)

In [ ]:
np.random.randint(-5, 6, (5,5))

In [ ]:
np.random.rand(5) # num of elements

In [ ]:
np.random.rand(10,5) # 10x10 matrix

In [ ]:
np.set_printoptions(precision=3) # set precision to 3
np.random.rand(10,5)

In [ ]:
x = [1,2,3,4,5]
np.diag(x)

In [ ]:
# reshape
np.arange(10).reshape(5,2)

In [ ]:
x = np.linspace(1, 5, 25).reshape(5,5)

In [ ]:
x.flatten()

In [ ]:
y = np.arange(1, 26).reshape(5,5)
print(y)

In [ ]:
y.T

maths

In [ ]:
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
print(a)
print(b)

In [ ]:
a + b

In [ ]:
a.dot(b) # dot product (matrix multiplication)

In [ ]:
a * b # element wise multiplication (not matrix multiplication)

In [ ]:
a / b 

In [ ]:
a - b

In [ ]:
a + 10 # add 10 to all elements

stats

In [ ]:
print(a.mean())
print(a.mean(axis=0)) # column wise mean
print(a.mean(axis=1)) # row wise mean

In [ ]:
print(a.sum())
print(a.sum(axis=0)) # column wise mean
print(a.sum(axis=1)) # row wise mean

In [ ]:
np.sin(a)

In [ ]:
print(np.cos(a))
print(np.tan(a))

In [101]:
print(np.exp(a))
print(np.sqrt(a))
print(np.max(a))
print(np.min(a))

[[8.103e+03 1.484e+02 1.097e+03]
 [5.460e+01 2.981e+03 7.389e+00]
 [5.460e+01 1.097e+03 4.034e+02]]
[[3.    2.236 2.646]
 [2.    2.828 1.414]
 [2.    2.646 2.449]]
9
2


In [109]:
x = np.random.randint(1, 100, (2,5))
print(x)

[[15 94 34 93 68]
 [36  7  2 85 81]]


In [111]:
print(x.max())    # max element
print(x.argmax()) # index of max element
print(x.min())    # min value element
print(x.argmin())

94
1
2
7
